name: Build Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y snapcraft fakeroot gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install dependencies
        run: npm install

      - name: Build for Linux ARM64
        run: npm run build:linux
        env:
          ELECTRON_BUILDER_ARCH: arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: release/
